version: "3.8"

services:
  db:
    image: postgres:16
    container_name: agri_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: agri_redis
    restart: always
    command: redis-server --requirepass agri123
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: agri_mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
      MP_UI_HTML_CHECK_BROWSER_ONLY: "true"

volumes:
  pgdata:
  redisdata: